# Generated by Django 4.1.7 on 2023-04-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminl', '0009_remove_brand_vendors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='category',
            name='allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='PARLEG', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.CharField(default='20%', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='productname',
            field=models.CharField(default='coldr', max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='productprice',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(default='milk', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.CharField(default='abc', max_length=50),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='allowed',
            field=models.BooleanField(default=False),
        ),
    ]
